version: "3.8"
services:
    web: 
        image: nginx:latest
        restart: always
        volumes:
            - ./data/public:/var/www/html
            - ./data/conf.d:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/nginx/ssl
            - ./data/certbot/data:/var/www/certbot
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email andrew@gaitskell.com --agree-tos --no-eff-email -d test.dmtools.info
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/logs:/var/log/letsencrypt
            - ./data/certbot/data:/var/www/certbot
